FROM ruby:2.4-alpine3.6
MAINTAINER SquareScale Engineering <engineering@squarescale.com>
LABEL maintainer "SquareScale Engineering <engineering@squarescale.com>"
LABEL name "SquareScale demo app"
LABEL version "dev"
ENV REFRESHED_AT 2017-05-02

WORKDIR /app/

RUN set -x \
  && apk add --no-cache \
    nodejs \
    postgresql-client \
    libgcrypt \
    libxml2 \
    libxslt \
    tzdata \
  && rm -rf /var/cache/apk/*

COPY Gemfile Gemfile.lock /app/

RUN set -x \
  && apk add --no-cache --virtual build-dep \
    build-base \
    postgresql-dev \
    libc-dev \
    curl-dev \
    libxml2-dev \
    libxslt-dev \
    linux-headers \
  && bundle config build.nokogiri --use-system-libraries \
  && bundle install --with development test \
  && apk del build-dep \
  && rm -rf /var/cache/apk/*

COPY . /app

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
